#ifndef ERRORCODE_H_INCLUDED
#define ERRORCODE_H_INCLUDED

const int CTOOL_1CD_ERROR = -50;

const int CTOOL_1CD_ARGUMENT_ERROR = CTOOL_1CD_ERROR - 20;
const int CTOOL_1CD_INVALID_ARGUMENT = CTOOL_1CD_ARGUMENT_ERROR - 1;

const int CTOOL_1CD_FILE_ERROR = CTOOL_1CD_ERROR - 30;
const int CTOOL_1CD_FILE_NOT_EXISTS  = CTOOL_1CD_FILE_ERROR - 1;
const int CTOOL_1CD_FILE_NOT_OPEN    = CTOOL_1CD_FILE_ERROR - 2;

#endif // ERRORCODE_H_INCLUDED
